import pandas as pd
df = pd.read_csv("03-a股多因子回测/data/raw/sz002384.csv")
print(df.head())
print(df.shape)
print(df.columns)
print(df.dtypes)
print(df.isna().sum())
print(df.duplicated().sum())
df['date'] = pd.to_datetime(df['date'])
print(df.dtypes)
print(df["date"].is_monotonic_increasing)
print((df["open"] <= 0).sum())
print((df["close"] <= 0).sum())
print((df["high"] <= 0).sum())
print((df["low"] <= 0).sum())
print((df["volume"] < 0).sum())
print((df["high"] < df["open"]).sum())
print((df["high"] < df["close"]).sum())
print((df["low"] > df["open"]).sum())
print((df["low"] > df["close"]).sum())
df.to_csv("03-a股多因子回测/data/processed/sz002384_clean.csv",index=False)